[package]
name = "linux-in-practice"
edition = "2024"

[[bin]]
name = "hello"

[[bin]]
name = "inf-loop"
path = "src/bin/inf_loop.rs"

[[bin]]
name = "syscall-inf-loop"
path = "src/bin/syscall_inf_loop.rs"

[[bin]]
name = "pause"

[[bin]]
name = "fork"

[dependencies]
libc = "0.2"
